--1. Tăng hệ số lương thêm 0.2 cho những giáo viên là trưởng khoa. 
UPDATE GIAOVIEN
SET HESO = HESO + 0.2
WHERE MAGV IN (SELECT TRGKHOA FROM KHOA);

--2. Cập nhật giá trị điểm trung bình tất cả các môn học (DIEMTB) của mỗi học viên
--(tất cả các môn học đều có hệ số 1 và nếu học viên thi một môn nhiều lần, chỉ lấy điểm của lần thi sau cùng). 
UPDATE HOCVIEN 
SET DIEMTB = (
    SELECT AVG(KETQUATHI.DIEM)
    FROM KETQUATHI 
    INNER JOIN (
        SELECT MAHV, MAMH, MAX(LANTHI) AS LANTHIMOINHAT
        FROM KETQUATHI
        GROUP BY MAHV, MAMH
    ) AS KQ_LANTHIMOINHAT
    ON KETQUATHI.MAHV = KQ_LANTHIMOINHAT.MAHV 
       AND KETQUATHI.MAMH = KQ_LANTHIMOINHAT.MAMH 
       AND KETQUATHI.LANTHI = KQ_LANTHIMOINHAT.LANTHIMOINHAT
    WHERE KETQUATHI.MAHV = HOCVIEN.MAHV);

--3. Cập nhật giá trị cho cột GHICHU là “Cam thi” đối với trường hợp: học viên có một môn bất kỳ thi lần thứ 3 dưới 5 điểm. 
UPDATE HOCVIEN
SET GHICHU = 'Cam thi'
WHERE MAHV IN (
    SELECT DISTINCT MAHV
    FROM KETQUATHI
    WHERE LANTHI = 3 AND DIEM < 5);

--4. Cập nhật giá trị cho cột XEPLOAI trong quan hệ HOCVIEN như sau: 
--Nếu DIEMTB >= 9 thì XEPLOAI =”XS” 
--Nếu  8 <= DIEMTB < 9 thì XEPLOAI = “G” 
--Nếu  6.5 <= DIEMTB < 8 thì XEPLOAI = “K” 
--Nếu  5  <=  DIEMTB < 6.5 thì XEPLOAI = “TB” 
--Nếu  DIEMTB < 5 thì XEPLOAI = ”Y” 
UPDATE HOCVIEN
SET XEPLOAI = 
    CASE 
        WHEN DIEMTB >= 9 THEN 'XS'
        WHEN DIEMTB >= 8 AND DIEMTB < 9 THEN 'G'
        WHEN DIEMTB >= 6.5 AND DIEMTB < 8 THEN 'K'
        WHEN DIEMTB >= 5 AND DIEMTB < 6.5 THEN 'TB'
        ELSE 'Y'
    END;
	


--6. Tìm tên những môn học mà giáo viên có tên “Tran Tam Thanh” dạy trong học kỳ 1 năm 2006. 
SELECT DISTINCT MONHOC.TENMH
FROM MONHOC 
INNER JOIN GIANGDAY ON MONHOC.MAMH = GIANGDAY.MAMH
INNER JOIN GIAOVIEN ON GIANGDAY.MAGV = GIAOVIEN.MAGV
WHERE GIAOVIEN.HOTEN = 'Tran Tam Thanh'
  AND GIANGDAY.HOCKY = 1
  AND GIANGDAY.NAM = 2006;

--7. Tìm những môn học (mã môn học, tên môn học) mà giáo viên chủ nhiệm lớp “K11” dạy trong học kỳ 1 năm 2006. 
SELECT DISTINCT MONHOC.MAMH, MONHOC.TENMH
FROM MONHOC 
INNER JOIN GIANGDAY ON MONHOC.MAMH = GIANGDAY.MAMH
INNER JOIN LOP ON GIANGDAY.MALOP = LOP.MALOP
INNER JOIN GIAOVIEN ON LOP.MAGVCN = GIAOVIEN.MAGV
WHERE LOP.TENLOP = 'K11'
  AND GIANGDAY.HOCKY = 1
  AND GIANGDAY.NAM = 2006;

--8. Tìm họ tên lớp trưởng của các lớp mà giáo viên có tên “Nguyen To Lan” dạy môn “Co So Du Lieu”. 
SELECT HOCVIEN.HO, HOCVIEN.TEN
FROM HOCVIEN 
INNER JOIN LOP ON HOCVIEN.MAHV = LOP.TRGLOP
INNER JOIN GIANGDAY ON LOP.MALOP = GIANGDAY.MALOP
INNER JOIN MONHOC ON GIANGDAY.MAMH = MONHOC.MAMH
INNER JOIN GIAOVIEN  ON GIANGDAY.MAGV = GIAOVIEN.MAGV
WHERE GIAOVIEN.HOTEN = 'Nguyen To Lan'
  AND MONHOC.TENMH = 'Co So Du Lieu';

--9. In ra danh sách những môn học (mã môn học, tên môn học) phải học liền trước môn “Co So Du Lieu”. 
SELECT MH_TRUOC.MAMH, MH_TRUOC.TENMH
FROM MONHOC 
INNER JOIN DIEUKIEN ON MONHOC.MAMH = DIEUKIEN.MAMH
INNER JOIN MONHOC MH_TRUOC ON DIEUKIEN.MAMH_TRUOC = MH_TRUOC.MAMH
WHERE MONHOC.TENMH = 'Co So Du Lieu';

--10. Môn “Cau Truc Roi Rac” là môn bắt buộc phải học liền trước những môn học (mã môn học, tên môn học) nào.
SELECT MH_SAU.MAMH, MH_SAU.TENMH
FROM MONHOC MH
INNER JOIN DIEUKIEN DK ON MH.MAMH = DK.MAMH_TRUOC
INNER JOIN MONHOC MH_SAU ON DK.MAMH = MH_SAU.MAMH
WHERE MH.TENMH = 'Cau Truc Roi Rac';

--11. Tìm họ tên giáo viên dạy môn CTRR cho cả hai lớp “K11” và “K12” trong cùng học kỳ 1 năm 2006. 
SELECT GIAOVIEN.HOTEN
FROM GIAOVIEN 
INNER JOIN GIANGDAY ON GIAOVIEN.MAGV = GIANGDAY.MAGV
INNER JOIN MONHOC ON GIANGDAY.MAMH = MONHOC.MAMH
WHERE MONHOC.MAMH = 'CTRR'
  AND GIANGDAY.HOCKY = 1
  AND GIANGDAY.NAM = 2006
  AND GIANGDAY.MALOP IN ('K11', 'K12')
GROUP BY GIAOVIEN.HOTEN
HAVING COUNT(DISTINCT GIANGDAY.MALOP) = 2;

--12. Tìm những học viên (mã học viên, họ tên) thi không đạt môn CSDL ở lần thi thứ 1 nhưng chưa thi lại môn này. 
SELECT HOCVIEN.MAHV, HOCVIEN.HO, HOCVIEN.TEN
FROM HOCVIEN 
INNER JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
INNER JOIN MONHOC MONHOC ON KETQUATHI.MAMH = MONHOC.MAMH
WHERE MONHOC.TENMH = 'Co So Du Lieu'
  AND KETQUATHI.LANTHI = 1
  AND KETQUATHI.DIEM < 5
  AND NOT EXISTS (
    SELECT 1 FROM KETQUATHI KETQUATHI2
    WHERE KETQUATHI2.MAHV = HOCVIEN.MAHV
      AND KETQUATHI2.MAMH = KETQUATHI.MAMH
      AND KETQUATHI2.LANTHI > 1
);

--13. Tìm giáo viên (mã giáo viên, họ tên) không được phân công giảng dạy bất kỳ môn học nào. 
SELECT GIAOVIEN.MAGV, HOTEN
FROM GIAOVIEN 
LEFT JOIN GIANGDAY ON GIAOVIEN.MAGV = GIANGDAY.MAGV
WHERE GIANGDAY.MAGV IS NULL;

--14. Tìm giáo viên (mã giáo viên, họ tên) không được phân công giảng dạy bất kỳ môn học nào thuộc khoa giáo viên đó phụ trách. 
SELECT GIAOVIEN.MAGV, GIAOVIEN.HOTEN
FROM GIAOVIEN 
LEFT JOIN GIANGDAY ON GIAOVIEN.MAGV = GIANGDAY.MAGV
LEFT JOIN MONHOC ON GIANGDAY.MAMH = MONHOC.MAMH
WHERE MONHOC.MAKHOA = GIAOVIEN.MAKHOA
  AND MONHOC.MAMH IS NULL;

--15. Tìm họ tên các học viên thuộc lớp “K11” thi một môn bất kỳ quá 3 lần vẫn “Khong dat” hoặc thi lần thứ 2 môn CTRR được 5 điểm. 
SELECT HOCVIEN.HO, HOCVIEN.TEN
FROM HOCVIEN 
INNER JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
INNER JOIN LOP ON HOCVIEN.MALOP = LOP.MALOP
INNER JOIN MONHOC ON KETQUATHI.MAMH = MONHOC.MAMH
WHERE LOP.TENLOP = 'K11'
  AND (
    (KETQUATHI.LANTHI > 3 AND KETQUATHI.KQUA = 'Khong dat')
    OR (MONHOC.TENMH = 'Cau Truc Roi Rac' AND KETQUATHI.LANTHI = 2 AND KETQUATHI.DIEM = 5));

--16. Tìm họ tên giáo viên dạy môn CTRR cho ít nhất hai lớp trong cùng một học kỳ của một năm học. 
SELECT GIAOVIEN.HOTEN
FROM GIAOVIEN 
INNER JOIN GIANGDAY ON GIAOVIEN.MAGV = GIANGDAY.MAGV
INNER JOIN MONHOC ON GIANGDAY.MAMH = MONHOC.MAMH
WHERE MONHOC.TENMH = 'Cau Truc Roi Rac'
GROUP BY GIAOVIEN.HOTEN, GIANGDAY.HOCKY, GIANGDAY.NAM
HAVING COUNT(DISTINCT GIANGDAY.MALOP) >= 2;

--17. Danh sách học viên và điểm thi môn CSDL (chỉ lấy điểm của lần thi sau cùng). 
SELECT HOCVIEN.MAHV, HOCVIEN.HO, HOCVIEN.TEN, KETQUATHI.DIEM
FROM HOCVIEN
INNER JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
INNER JOIN MONHOC ON KETQUATHI.MAMH = MONHOC.MAMH
WHERE MONHOC.TENMH = 'Co So Du Lieu'
  AND KETQUATHI.NGTHI = (
    SELECT MAX(KQ2.NGTHI)
    FROM KETQUATHI AS KQ2
    WHERE KQ2.MAHV = HOCVIEN.MAHV
      AND KQ2.MAMH = KETQUATHI.MAMH);

--18. Danh sách học viên và điểm thi môn “Co So Du Lieu” (chỉ lấy điểm cao nhất của các lần thi). 
SELECT HOCVIEN.MAHV, HOCVIEN.HO, HOCVIEN.TEN, MAX(KETQUATHI.DIEM) AS DIEM
FROM HOCVIEN
INNER JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
INNER JOIN MONHOC ON KETQUATHI.MAMH = MONHOC.MAMH
WHERE MONHOC.TENMH = 'Co So Du Lieu'
GROUP BY HOCVIEN.MAHV, HOCVIEN.HO, HOCVIEN.TEN;