--1. Tạo quan hệ và khai báo tất cả các ràng buộc khóa chính, khóa ngoại. Thêm vào 3 thuộc tính GHICHU, DIEMTB, XEPLOAI cho quan hệ HOCVIEN. 
CREATE TABLE HOCVIEN
(
	MAHV char(5) NOT NULL,
	HO varchar(40),
	TEN varchar(10),
	NGSINH smalldatetime,
	GIOITINH varchar(3),
	NOISINH varchar(40),
	MALOP char(3),
	CONSTRAINT PK_HV PRIMARY KEY (MAHV),
	
);

ALTER TABLE HOCVIEN
ADD CONSTRAINT FK_HV FOREIGN KEY (MALOP) REFERENCES LOP(MALOP);

ALTER TABLE HOCVIEN
ADD GHICHU VARCHAR(40), DIEMTB numeric (4,2), XEPLOAI VARCHAR(20);

CREATE TABLE KHOA
( 
	MAKHOA varchar(4) NOT NULL,
	TENKHOA varchar(40),
	NGTLAP smalldatetime,
	TRGKHOA char(4) NOT NULL,
	CONSTRAINT PK_KHOA PRIMARY KEY (MAKHOA)
);

ALTER TABLE KHOA
ADD CONSTRAINT FK_KHOA FOREIGN KEY (TRGKHOA) REFERENCES GIAOVIEN(MAGV);

CREATE TABLE MONHOC
(
	MAMH varchar(10) NOT NULL,
	TENMH varchar(40),
	TCLT tinyint,
	TCTH tinyint,
	MAKHOA varchar(4),
	CONSTRAINT PK_MH PRIMARY KEY (MAMH)
);

ALTER TABLE MONHOC
ADD CONSTRAINT FK_MH FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA);

CREATE TABLE GIAOVIEN 
(
	MAGV char(4) NOT NULL,
	HOTEN varchar(40),
	HOCVI varchar(10),
	HOCHAM varchar(10),
	GIOITINH varchar(3),
	NGSINH smalldatetime,
	NGVL smalldatetime,
	HESO numeric(4,2),
	MUCLUONG money,
	MAKHOA varchar(4),
	CONSTRAINT PK_GV PRIMARY KEY (MAGV)
);

ALTER TABLE GIAOVIEN
ADD CONSTRAINT FK_GV FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA);

CREATE TABLE DIEUKIEN
(
	MAMH varchar(10) NOT NULL,
	MAMH_TRUOC varchar(10) NOT NULL,
	CONSTRAINT PK_DK PRIMARY KEY (MAMH, MAMH_TRUOC)
);

ALTER TABLE DIEUKIEN
ADD CONSTRAINT FK_DK1 FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
	CONSTRAINT FK_DK2 FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC(MAMH);

CREATE TABLE LOP
(
	MALOP char(3) NOT NULL,
	TENLOP varchar(40),
	TRGLOP char(5),
	SISO tinyint,
	MAGVCN char(4),
	CONSTRAINT PK_LOP PRIMARY KEY (MALOP)
);

ALTER TABLE LOP
ADD CONSTRAINT FK_LOP FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV);

CREATE TABLE GIANGDAY
(
	MALOP char(3) NOT NULL,
	MAMH varchar(10) NOT NULL,
	MAGV char(4),
	HOCKY tinyint,
	NAM smallint,
	TUNGAY smalldatetime,
	DENNGAY smalldatetime,
	CONSTRAINT PK_GD PRIMARY KEY (MALOP, MAMH),
	CONSTRAINT FK_GD FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV)
);

CREATE TABLE KETQUATHI
(
	MAHV char(5) NOT NULL,
	MAMH varchar(10) NOT NULL,
	LANTHI tinyint NOT NULL,
	NGTHI smalldatetime,
	DIEM numeric (4,2),
	KQUA varchar(10),
	CONSTRAINT PK_KQT PRIMARY KEY (MAHV, MAMH, LANTHI),
	CONSTRAINT FK_KQT1 FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV),
	CONSTRAINT FK_KQT2 FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
);

--3. Thuộc tính GIOITINH chỉ có giá trị là “Nam” hoặc “Nu”.
ALTER TABLE GIAOVIEN
ADD CONSTRAINT CHK_GIOITINH_GV CHECK (GIOITINH IN('Nam', 'Nu'));

ALTER TABLE HOCVIEN
ADD CONSTRAINT CHK_GIOITINH_HV CHECK (GIOITINH IN('Nam', 'Nu'));

--4. Điểm số của một lần thi có giá trị từ 0 đến 10 và cần lưu đến 2 số lẽ (VD: 6.22).
ALTER TABLE KETQUATHI
ALTER COLUMN DIEM numeric (4,2);

ALTER TABLE KETQUATHI
ADD CONSTRAINT CHK_DIEM CHECK (DIEM <= 10.0 AND DIEM >= 0.0);

--5. Kết quả thi là “Dat” nếu điểm từ 5 đến 10 và “Khong dat” nếu điểm nhỏ hơn 5.
ALTER TABLE KETQUATHI
ADD CONSTRAINT CHK_KQUA CHECK (
(DIEM >= 5 AND DIEM <= 10 AND KQUA = 'Dat') OR
(DIEM <= 5 AND DIEM >= 0 AND KQUA = 'Khong dat'));

--6. Học viên thi một môn tối đa 3 lần.
ALTER TABLE KETQUATHI
ADD CONSTRAINT CHK_LANTHI CHECK (LANTHI <= 3);

--7. Học kỳ chỉ có giá trị từ 1 đến 3.
ALTER TABLE GIANGDAY
ADD CONSTRAINT CHK_HOCKY CHECK (HOCKY >= 1 AND HOCKY <= 3);

--8. Học vị của giáo viên chỉ có thể là “CN”, “KS”, “Ths”, ”TS”, ”PTS”.
ALTER TABLE GIAOVIEN
ADD CONSTRAINT CHK_HOCVI CHECK (HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS'));











