--12. Tìm các số hóa đơn đã mua sản phẩm có mã số “BB01” hoặc “BB02”, mỗi sản phẩm mua với số lượng từ 10 đến 20
SELECT DISTINCT SOHD
FROM CTHD
WHERE MASP IN ('BB01', 'BB02') 
AND SL BETWEEN 10 AND 20;

--13. Tìm các số hóa đơn mua cùng lúc 2 sản phẩm có mã số “BB01” và “BB02”, mỗi sản phẩm mua với số lượng từ 10 đến 20.
SELECT SOHD
FROM CTHD
WHERE (MASP = 'BB01' AND SL BETWEEN 10 AND 20)
   OR (MASP = 'BB02' AND SL BETWEEN 10 AND 20)
GROUP BY SOHD
HAVING COUNT(DISTINCT MASP) = 2;

--14. In ra danh sách các sản phẩm (MASP,TENSP) do “Trung Quoc” sản xuất hoặc các sản phẩm được bán ra trong ngày 1/1/2007. 
SELECT DISTINCT SANPHAM.MASP, SANPHAM.TENSP
FROM SANPHAM 
LEFT JOIN CTHD ON SANPHAM.MASP = CTHD.MASP
LEFT JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
WHERE SANPHAM.NUOCSX = 'Trung Quoc'
   OR HOADON.NGHD = '2007-01-01';

--15. In ra danh sách các sản phẩm (MASP,TENSP) không bán được. 
SELECT SANPHAM.MASP, SANPHAM.TENSP
FROM SANPHAM 
LEFT JOIN CTHD ON SANPHAM.MASP = CTHD.MASP
WHERE CTHD.MASP IS NULL;

--16. In ra danh sách các sản phẩm (MASP,TENSP) không bán được trong năm 2006. 
SELECT SANPHAM.MASP, SANPHAM.TENSP
FROM SANPHAM 
LEFT JOIN CTHD ON SANPHAM.MASP = CTHD.MASP
LEFT JOIN HOADON ON CTHD.SOHD = HOADON.SOHD AND YEAR(HOADON.NGHD) = 2006
WHERE HOADON.SOHD IS NULL;


--17. In ra danh sách các sản phẩm (MASP,TENSP) do “Trung Quoc” sản xuất không bán được trong năm 2006. 
SELECT SANPHAM.MASP, SANPHAM.TENSP
FROM SANPHAM 
LEFT JOIN CTHD ON SANPHAM.MASP = CTHD.MASP
LEFT JOIN HOADON ON CTHD.SOHD = HOADON.SOHD AND YEAR(HOADON.NGHD) = 2006
WHERE HOADON.SOHD IS NULL AND NUOCSX = 'Trung Quoc';

--18. Tìm số hóa đơn trong năm 2006 đã mua ít nhất tất cả các sản phẩm do Singapore sản xuất.
SELECT HOADON.SOHD
FROM HOADON 
INNER JOIN CTHD ON HOADON.SOHD = CTHD.SOHD
INNER JOIN SANPHAM ON CTHD.MASP = SANPHAM.MASP
WHERE HOADON.NGHD BETWEEN '2006-01-01' AND '2006-12-31'
  AND SANPHAM.NUOCSX = 'Singapore'
GROUP BY HOADON.SOHD
HAVING COUNT(DISTINCT SANPHAM.MASP) = (SELECT COUNT(DISTINCT MASP) FROM SANPHAM WHERE NUOCSX = 'Singapore');
